### ISSUE TITLE
Del tg acc ajg 👀

### ISSUE THREAD

**Issue by tomiprs0x** [adekmaulana/UAS#1]

**Comment by adekmaulana** [comment]
hmmmmmmmmmmmmmmmmmm

**Comment by tomiprs0x** [comment]
Selese UAS janjinya tepatin yak . Thxby 🍂

**Comment by tomiprs0x** [comment]
Dek lihat ini

https://github.com/X-Newbie/X-NEWBIE

**Comment by adekmaulana** [comment]
awkowaowkawowak copy pasta

**Comment by tomiprs0x** [comment]
Yaudahlah ya kalo diprivate juga percuma, gak ada yg lihat 😂
